[package]
name = "kmer-functional-profiler-core"
description = "Kernels: FASTX streaming, translation, amino-acid k-mers, hashing, samplers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true
